---
# Source: harbor/templates/notary/notary-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kccr-harbor-notary-server
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
    component: notary-server
spec:
  replicas: 1
  selector:
    matchLabels:
      release: kccr
      app: "harbor"
      component: notary-server
  template:
    metadata:
      labels:
        heritage: Helm
        release: kccr
        chart: harbor
        app: "harbor"
        component: notary-server
      annotations:
        checksum/secret: 6c1d0da5c8813097d3f0fa659e390ce90874ad349fe409b91923209efa1ba796
        checksum/secret-core: 98f7f201d0d484c51abf560d66c9827c57026960f5d02e6986577285675fa5c6
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      serviceAccountName: kccr-sa
      automountServiceAccountToken: false
      containers:
      - name: notary-server
        image: goharbor/notary-server-photon:v2.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /_notary_server/health
            scheme: "HTTP"
            port: 4443
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_notary_server/health
            scheme: "HTTP"
            port: 4443
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: MIGRATIONS_PATH
          value: migrations/server/postgresql
        - name: DB_URL
          value: postgres://postgres:changeit@kccr-harbor-database:5432/notaryserver?sslmode=disable
        volumeMounts:
        - name: config
          mountPath: /etc/notary/server-config.postgres.json
          subPath: server.json
        - name: token-service-certificate
          mountPath: /root.crt
          subPath: tls.crt
        - name: signer-certificate
          mountPath: /etc/ssl/notary/ca.crt
          subPath: ca.crt
      volumes:
      - name: config
        secret:
          secretName: "kccr-harbor-notary-server"
      - name: token-service-certificate
        secret:
          secretName: kccr-harbor-core
      - name: signer-certificate
        secret:
          secretName: kccr-harbor-notary-server
