---
# Source: harbor/templates/jobservice/jobservice-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kccr-harbor-jobservice"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
    component: jobservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      release: kccr
      app: "harbor"
      component: jobservice
  template:
    metadata:
      labels:
        heritage: Helm
        release: kccr
        chart: harbor
        app: "harbor"
        component: jobservice
      annotations:
        checksum/configmap: 160aa7cbcea35acbbf7301f77c5db8fb4de27538824fa6ff00383e6d2e39d07b
        checksum/configmap-env: 19538ee96b7a84aa15ac3e176d08b199710d31dc1edbe08692b0b83561ef0160
        checksum/secret: 33894a2f237b024cbb486e2259795cc8fb47283d2f372bf5887c0e207647ed35
        checksum/secret-core: e9f638bfe109a228240f29b41efc4ae07fc280dc4a31d6cdb1dec5d87e2c703c
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      serviceAccountName: kccr-sa
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: jobservice
        image: goharbor/harbor-jobservice:v2.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/v1/stats
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: kccr-harbor-core
                key: secret
        envFrom:
        - configMapRef:
            name: "kccr-harbor-jobservice-env"
        - secretRef:
            name: "kccr-harbor-jobservice"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/config.yml
          subPath: config.yml
        - name: job-logs
          mountPath: /var/log/jobs
          subPath: 
      volumes:
      - name: jobservice-config
        configMap:
          name: "kccr-harbor-jobservice"
      - name: job-logs
        persistentVolumeClaim:
          claimName: kccr-harbor-jobservice
