---
# Source: harbor/templates/jobservice/jobservice-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "kccr-harbor-jobservice"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: http-jobservice
      port: 80
      targetPort: 8080
  selector:
    release: kccr
    app: "harbor"
    component: jobservice
