---
# Source: harbor/templates/chartmuseum/chartmuseum-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "kccr-harbor-chartmuseum"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
data:
  PORT: "9999"
  CACHE: "redis"
  CACHE_REDIS_ADDR: "kccr-harbor-redis:6379"
  CACHE_REDIS_DB: "3"
  BASIC_AUTH_USER: "chart_controller"
  DEPTH: "1"
  DEBUG: "false"
  LOG_JSON: "true"
  DISABLE_METRICS: "false"
  DISABLE_API: "false"
  DISABLE_STATEFILES: "false"
  ALLOW_OVERWRITE: "true"
  AUTH_ANONYMOUS_GET: "false"
  CONTEXT_PATH: ""
  INDEX_LIMIT: "0"
  MAX_STORAGE_OBJECTS: "0"
  MAX_UPLOAD_SIZE: "20971520"
  CHART_POST_FORM_FIELD_NAME: "chart"
  PROV_POST_FORM_FIELD_NAME: "prov"
  STORAGE: "amazon"
  STORAGE_AMAZON_BUCKET: kccr-data
  STORAGE_AMAZON_REGION: bd-mir-1
  STORAGE_AMAZON_ENDPOINT: https://kcs3.bd-mir-1.klovercloud.io
  AWS_ACCESS_KEY_ID: MbhnAKjqWrLkgNnU
  STORAGE_TIMESTAMP_TOLERANCE: 1s
