---
# Source: harbor/templates/chartmuseum/chartmuseum-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "kccr-harbor-chartmuseum"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
type: Opaque
data:
  CACHE_REDIS_PASSWORD: ""
  AWS_SECRET_ACCESS_KEY: "UHhQZ0hFd01YS09yV2R4ZA=="
